// @ts-check
/** Progressive enhancement. The same HTML works without this script. */
(() => {
  /** @type {AbortController | null} */ let lifecycle=null;
  /** @type {ReturnType<typeof setTimeout> | undefined} */ let toastTimer;
  /** @type {ReturnType<typeof setTimeout> | undefined} */ let searchTimer;
  /** @type {import('../types').PageData} */
  const data = window.__SITE_DATA__ || JSON.parse(document.getElementById('site-data')?.textContent || '{}');
  if(!data?.previews || !data?.search) return;
  const previewById = new Map(data.previews.map(x=>[x.id,x]));
  /** @param {string} key @returns {string[]} */
  function stored(key) { try {const value=JSON.parse(localStorage.getItem('interchange:'+key)||'[]');return Array.isArray(value)?value.filter(v=>typeof v==='string'&&previewById.has(v)):[];} catch{return [];} }
  /** @param {string} key @param {string[]} value */
  function store(key,value) {try{localStorage.setItem('interchange:'+key,JSON.stringify(value));return true;}catch{return false;}}
  /** @param {string} message */
  function toast(message){const box=document.querySelector('.toast');if(!(box instanceof HTMLElement))return;box.textContent=message;box.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{box.hidden=true;},3200);}
  /** @param {string} text @param {string} success */
  async function copy(text,success){try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text);}else{const field=document.createElement('textarea');field.value=text;field.style.position='fixed';field.style.opacity='0';document.body.append(field);field.select();const ok=document.execCommand('copy');field.remove();if(!ok)throw Error('Clipboard unavailable');}toast(success);}catch{toast('Clipboard unavailable. Select and copy the text manually.');}}
  function updateSaved(){const ids=stored('saved');document.querySelectorAll('[data-save]').forEach(el=>{const id=el.getAttribute('data-save');const saved=id!==null&&ids.includes(id);el.setAttribute('aria-pressed',String(saved));el.textContent=saved?'✓ Saved station':'+ Save station';});document.querySelectorAll('[data-saved-count]').forEach(el=>{el.textContent=ids.length?`(${ids.length})`:'';});document.querySelectorAll('[data-saved-row]').forEach(el=>{if(el instanceof HTMLElement)el.hidden=!ids.includes(el.dataset.savedRow||'');});const empty=document.querySelector('[data-saved-empty]');if(empty instanceof HTMLElement)empty.hidden=ids.length>0;}
  /** @param {HTMLElement} scope @param {string} query */
  function renderResults(scope,query){const container=scope.querySelector('[data-search-results]');const status=scope.querySelector('[data-search-status]');if(!container||!status)return;container.replaceChildren();if(!query.trim()){status.textContent='SEARCH 36 STATIONS AND THEIR SOURCE PERSPECTIVES.';return;}const results=rankSearch(data.search,query);status.textContent=results.length?`${results.length} MATCHING STATION${results.length===1?'':'S'}${results.length===12?' · BEST MATCHES FIRST':''}`:'NO MATCHES. TRY A BROADER TERM OR A STATION NUMBER.';for(const item of results){const a=document.createElement('a');a.className='search-result';a.href=item.url;const id=document.createElement('span');id.className='mono';id.textContent=String(item.number).padStart(2,'0');const content=document.createElement('div');const title=document.createElement('h3');title.textContent=item.short;const summary=document.createElement('p');summary.textContent=item.summary;content.append(title,summary);const ar=document.createElement('span');ar.textContent='↗';ar.setAttribute('aria-hidden','true');a.append(id,content,ar);container.append(a);}}
  function boot(){
    lifecycle?.abort();lifecycle=new AbortController();const signal=lifecycle.signal;
    clearTimeout(searchTimer);clearTimeout(toastTimer);
    updateSaved();
    const stationPage=document.querySelector('[data-station-page]');if(stationPage){const id=stationPage.getAttribute('data-station-page');if(id)store('visited',[...new Set([...stored('visited'),id])]);}
    document.querySelectorAll('[data-save]').forEach(el=>el.addEventListener('click',()=>{const id=el.getAttribute('data-save');if(!id)return;let ids=stored('saved');ids=ids.includes(id)?ids.filter(x=>x!==id):[...ids,id];if(store('saved',ids)){updateSaved();toast(ids.includes(id)?'Station saved locally on this device.':'Station removed from this device.');}else{toast('Browser storage is unavailable. Save the station link instead.');}},{signal}));
    document.querySelectorAll('[data-copy-link]').forEach(el=>el.addEventListener('click',()=>{if(window.__OFFLINE__){void copy(location.href,'Local preview link copied. Share the HTML file with it.');}else{void copy(location.href,'Station link copied.');}},{signal}));
    document.querySelectorAll('[data-copy-artifact]').forEach(el=>el.addEventListener('click',()=>{const text=el.closest('.working-artifact')?.querySelector('p:not(.meta)')?.textContent||'';void copy(text,'Working artifact copied.');},{signal}));
    document.querySelectorAll('[data-clear-storage]').forEach(el=>el.addEventListener('click',()=>{const success=store('saved',[])&&store('visited',[]);updateSaved();toast(success?'Saved and visited stations cleared.':'Browser storage is unavailable.');},{signal}));
    document.querySelectorAll('[data-source-out]').forEach(el=>el.addEventListener('click',()=>{window.dispatchEvent(new CustomEvent('interchange:source-out',{detail:{source:el.getAttribute('data-source-out')}}));},{signal}));
    // Native dialog has keyboard containment, Escape and a real fallback search URL.
    const dialog=document.getElementById('search-dialog');let lastFocus=document.activeElement;
    const openSearch=()=>{if(!(dialog instanceof HTMLDialogElement))return;lastFocus=document.activeElement;dialog.showModal();const input=dialog.querySelector('input');input?.focus();};
    document.querySelectorAll('.search-trigger').forEach(el=>el.addEventListener('click',event=>{event.preventDefault();openSearch();},{signal}));
    document.querySelector('[data-close-search]')?.addEventListener('click',()=>{if(dialog instanceof HTMLDialogElement)dialog.close();},{signal});
    dialog?.addEventListener('close',()=>{if(lastFocus instanceof HTMLElement)lastFocus.focus();},{signal});
    dialog?.addEventListener('click',event=>{if(!(dialog instanceof HTMLDialogElement))return;if(event.target===dialog){const box=dialog.getBoundingClientRect();const e=/** @type {MouseEvent} */(event);if(e.clientX<box.left||e.clientX>box.right||e.clientY<box.top||e.clientY>box.bottom)dialog.close();}},{signal});
    document.addEventListener('keydown',event=>{const target=event.target;const editing=target instanceof HTMLElement&&(target.matches('input,textarea,select')||target.isContentEditable);if((event.key==='/'&&!editing)||((event.ctrlKey||event.metaKey)&&event.key==='k')){event.preventDefault();openSearch();}},{signal});
    document.querySelectorAll('[data-search-input]').forEach(el=>{if(!(el instanceof HTMLInputElement))return;const scope=el.closest('dialog')||el.closest('main');if(!(scope instanceof HTMLElement))return;el.addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>renderResults(scope,el.value),90);},{signal});});
    // Text index: no layout or source details enter the search query pipeline.
    let filter='all';const indexInput=document.querySelector('[data-index-query]');
    const filterIndex=()=>{const query=indexInput instanceof HTMLInputElement?normaliseQuery(indexInput.value):'';let count=0;document.querySelectorAll('.index-line .station-row').forEach(el=>{if(!(el instanceof HTMLElement))return;const matches=(filter==='all'||el.dataset.indexLine===filter)&&normaliseQuery(el.dataset.searchText||'').includes(query);el.hidden=!matches;if(matches)count++;});document.querySelectorAll('[data-index-section]').forEach(el=>{if(el instanceof HTMLElement)el.hidden=!Array.from(el.querySelectorAll('.station-row')).some(row=>row instanceof HTMLElement&&!row.hidden);});const countEl=document.querySelector('[data-index-count]');if(countEl)countEl.textContent=`${count} station${count===1?'':'s'}`;const empty=document.querySelector('[data-index-empty]');if(empty instanceof HTMLElement)empty.hidden=count>0;};
    indexInput?.addEventListener('input',filterIndex,{signal});document.querySelectorAll('[data-index-filter]').forEach(el=>el.addEventListener('click',()=>{filter=el.getAttribute('data-index-filter')||'all';document.querySelectorAll('[data-index-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===el)));filterIndex();},{signal}));
    const sourceInput=document.querySelector('[data-source-query]');sourceInput?.addEventListener('input',()=>{if(!(sourceInput instanceof HTMLInputElement))return;const query=normaliseQuery(sourceInput.value);let count=0;document.querySelectorAll('[data-source-filter]').forEach(el=>{if(!(el instanceof HTMLElement))return;el.hidden=!normaliseQuery(el.dataset.sourceFilter||'').includes(query);if(!el.hidden)count++;});const label=document.querySelector('[data-source-count]');if(label)label.textContent=`${count} matching source${count===1?'':'s'}`;const empty=document.querySelector('[data-source-empty]');if(empty instanceof HTMLElement)empty.hidden=count>0;},{signal});
    // Fixed geometry: only emphasis changes when a line or interchange is focused.
    const svg=document.querySelector('.metro-map');const detail=document.getElementById('line-detail');const reset=document.querySelector('[data-reset-network]');
    let selected='';
    /** @param {string[]} ids */
    const emphasize=ids=>{if(!svg)return;if(ids.length)svg.setAttribute('data-active-lines',ids.join(' '));else svg.removeAttribute('data-active-lines');svg.querySelectorAll('[data-network-part]').forEach(el=>{const own=(el.getAttribute('data-lines')||'').split(' ');el.classList.toggle('is-muted',ids.length>0&&!own.some(id=>ids.includes(id)));});};
    /** @param {string} line @param {boolean} move */
    const setLine=(line,move=false)=>{selected=line;emphasize(line?[line]:[]);document.querySelectorAll('[data-select-line]').forEach(el=>{const active=el.getAttribute('data-select-line')===line;if(active)el.setAttribute('aria-current','true');else el.removeAttribute('aria-current');el.setAttribute('aria-expanded',String(active));el.classList.toggle('is-dimmed',Boolean(line)&&!active);});document.querySelectorAll('[data-line-panel]').forEach(el=>{if(el instanceof HTMLElement)el.hidden=el.dataset.linePanel!==line;});if(detail)detail.hidden=!line;if(reset instanceof HTMLElement)reset.hidden=!line;const status=document.getElementById('line-state');if(status)status.textContent=line?`Line ${line} · ${data.previews.filter(s=>s.line===line).length} stations`:'Six lines · 36 stations';if(move&&matchMedia('(max-width:1200px)').matches&&line){detail?.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});}};
    document.querySelectorAll('[data-select-line]').forEach(el=>{el.addEventListener('click',event=>{event.preventDefault();const value=el.getAttribute('data-select-line')||'';setLine(selected===value?'':value,true);},{signal});el.addEventListener('pointerenter',()=>emphasize([el.getAttribute('data-select-line')||'']),{signal});el.addEventListener('pointerleave',()=>emphasize(selected?[selected]:[]),{signal});});
    reset?.addEventListener('click',()=>setLine(''),{signal});
    const tooltip=document.getElementById('station-tooltip');const canvas=document.getElementById('network');
    /** @param {Element} el */
    const showTip=el=>{const id=el.getAttribute('data-station');const s=id?previewById.get(id):null;if(!s||!tooltip||!canvas)return;tooltip.querySelector('[data-tip-meta]')?.replaceChildren(document.createTextNode(`Station ${String(s.number).padStart(2,'0')} · Line ${s.line}`));tooltip.querySelector('[data-tip-title]')?.replaceChildren(document.createTextNode(s.title));tooltip.querySelector('[data-tip-summary]')?.replaceChildren(document.createTextNode(s.summary));tooltip.hidden=false;const a=el.getBoundingClientRect();const box=canvas.getBoundingClientRect();const tipWidth=tooltip.offsetWidth;let left=a.left-box.left+22;let top=a.top-box.top-35;if(left+tipWidth>box.width-5)left=a.left-box.left-tipWidth-18;left=Math.max(4,left);top=Math.max(0,Math.min(top,box.height-tooltip.offsetHeight-5));tooltip.style.left=`${left}px`;tooltip.style.top=`${top}px`;el.setAttribute('aria-describedby','station-tooltip');};
    const hideTip=()=>{if(tooltip)tooltip.hidden=true;svg?.querySelectorAll('[aria-describedby="station-tooltip"]').forEach(el=>el.removeAttribute('aria-describedby'));};
    svg?.querySelectorAll('[data-station]').forEach(el=>{el.addEventListener('pointerenter',()=>showTip(el),{signal});el.addEventListener('pointerleave',hideTip,{signal});el.addEventListener('focus',()=>showTip(el),{signal});el.addEventListener('blur',hideTip,{signal});});
    svg?.querySelectorAll('.transfer-mark').forEach(el=>{el.addEventListener('pointerenter',()=>emphasize((el.getAttribute('data-lines')||'').split(' ')),{signal});el.addEventListener('pointerleave',()=>emphasize(selected?[selected]:[]),{signal});el.addEventListener('focusin',()=>emphasize((el.getAttribute('data-lines')||'').split(' ')),{signal});el.addEventListener('focusout',()=>emphasize(selected?[selected]:[]),{signal});});
    document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!(dialog instanceof HTMLDialogElement&&dialog.open)){hideTip();setLine('');}},{signal});
    const currentURL=window.__OFFLINE__?new URL('https://preview.invalid'+(location.hash.slice(1)||'/')):new URL(location.href);
    const fromLine=currentURL.searchParams.get('line');if(fromLine&&/^[A-F]$/.test(fromLine))setLine(fromLine);
    const fromStation=currentURL.searchParams.get('station');if(fromStation&&previewById.has(fromStation)){svg?.querySelector(`[data-station="${fromStation}"]`)?.classList.add('is-current');}
    // The article's margin anchors reflect actual scroll position without moving content.
    if('IntersectionObserver' in window&&document.querySelector('.article-rail nav')){const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting){document.querySelectorAll('.article-rail nav a').forEach(a=>{if(a.getAttribute('href')==='#'+entry.target.id)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});}}},{rootMargin:'-90px 0px -65% 0px',threshold:0});document.querySelectorAll('.reading-document>section[id]').forEach(section=>observer.observe(section));signal.addEventListener('abort',()=>observer.disconnect(),{once:true});}
  }
  window.Interchange={boot,dispose:()=>{lifecycle?.abort();clearTimeout(searchTimer);clearTimeout(toastTimer);}};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
